"use client";

import * as React from "react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  FileText,
  Plus,
  Eye,
  Pencil,
  Download,
  ChevronDown,
  ChevronUp,
  Clock,
  CheckCircle2,
  AlertCircle,
  History,
  User,
  X,
} from "lucide-react";
import { usePolicies } from '@/hooks/use-governance';

interface PolicyVersion {
  version: string;
  date: string;
  author: string;
  summary: string;
}

interface Approver {
  name: string;
  role: string;
  status: "approved" | "pending" | "rejected";
  date?: string;
}

interface Policy {
  id: string;
  title: string;
  type: string;
  status: "approved" | "in_review" | "draft";
  version: string;
  lastUpdated: string;
  description: string;
  content: string;
  versions: PolicyVersion[];
  approvers: Approver[];
}

const DEMO_POLICIES: Policy[] = [
  {
    id: "pol-001",
    title: "AI Acceptable Use Policy (AUP)",
    type: "Acceptable Use",
    status: "approved",
    version: "2.1",
    lastUpdated: "Jan 15, 2026",
    description:
      "Defines acceptable and prohibited uses of AI coding assistants within the organization, including data handling requirements and authorized activities.",
    content: `AI ACCEPTABLE USE POLICY (AUP)
Version 2.1 | Effective Date: January 15, 2026
Classification: Internal - All Employees

1. PURPOSE AND SCOPE

This Acceptable Use Policy ("AUP") establishes guidelines and requirements for the use of AI-powered coding assistants (including but not limited to Claude Code, OpenAI Codex, and similar tools) within [Organization Name]. This policy applies to all employees, contractors, and third-party personnel who access or utilize AI coding tools in connection with organizational projects.

The objective of this policy is to maximize the productivity benefits of AI coding assistants while maintaining the organization's security posture, protecting intellectual property, and ensuring compliance with applicable laws and regulations.

2. AUTHORIZED ACTIVITIES

The following activities are authorized when using approved AI coding tools within the managed sandbox environment:

  a) Code generation and completion for approved project repositories
  b) Code review assistance and refactoring suggestions
  c) Documentation generation for internal codebases
  d) Unit test generation and test case creation
  e) Debugging assistance for non-sensitive application code
  f) Learning and skill development using non-proprietary examples

All authorized activities must occur within the organization's managed sandbox environment with approved configuration settings applied.

3. PROHIBITED ACTIVITIES

The following activities are strictly prohibited:

  a) Inputting classified, restricted, or personally identifiable information (PII) into AI tools
  b) Using AI tools to process customer data, financial records, or protected health information (PHI)
  c) Disabling or circumventing managed settings, DLP rules, or egress filtering controls
  d) Using personal AI tool accounts or subscriptions for organizational work
  e) Sharing AI-generated code externally without proper review and approval
  f) Using AI tools to generate code for security-critical components (authentication, encryption, access control) without mandatory human review
  g) Attempting to extract training data or reverse-engineer AI model behavior

4. DATA HANDLING REQUIREMENTS

  a) No proprietary algorithms, trade secrets, or confidential business logic shall be provided as context to AI tools
  b) All AI interactions are subject to audit logging and may be reviewed by the security team
  c) Code generated by AI tools must undergo the same review process as human-written code
  d) Developers must verify that AI-generated code does not inadvertently include licensed code or copyrighted material
  e) All data transmitted to AI services must traverse approved network paths with TLS encryption

5. COMPLIANCE AND ENFORCEMENT

Violations of this policy may result in:
  - Immediate revocation of AI tool access
  - Disciplinary action up to and including termination
  - Referral to legal counsel for potential regulatory violations

All employees must complete the AI Security Awareness Training module before being granted access to AI coding tools. Annual recertification is required.

6. REVIEW AND UPDATES

This policy will be reviewed quarterly by the AI Governance Committee and updated as necessary to reflect changes in technology, regulations, or organizational requirements.`,
    versions: [
      {
        version: "2.1",
        date: "Jan 15, 2026",
        author: "Sarah Chen",
        summary: "Updated data handling requirements for new DLP integration",
      },
      {
        version: "2.0",
        date: "Dec 1, 2025",
        author: "Sarah Chen",
        summary:
          "Major revision: added prohibited activities section, compliance enforcement",
      },
      {
        version: "1.1",
        date: "Oct 15, 2025",
        author: "James Rodriguez",
        summary: "Added sandbox environment requirements",
      },
      {
        version: "1.0",
        date: "Aug 1, 2025",
        author: "James Rodriguez",
        summary: "Initial policy creation",
      },
    ],
    approvers: [
      {
        name: "Maria Lopez",
        role: "CISO",
        status: "approved",
        date: "Jan 14, 2026",
      },
      {
        name: "David Kim",
        role: "CTO",
        status: "approved",
        date: "Jan 13, 2026",
      },
      {
        name: "Rachel Foster",
        role: "Legal Counsel",
        status: "approved",
        date: "Jan 12, 2026",
      },
    ],
  },
  {
    id: "pol-002",
    title: "Incident Response Plan Addendum",
    type: "Incident Response",
    status: "in_review",
    version: "1.0",
    lastUpdated: "Feb 1, 2026",
    description:
      "Addendum to the existing IRP covering AI-specific security incidents including model misuse, data leakage through AI tools, and unauthorized AI access scenarios.",
    content: `INCIDENT RESPONSE PLAN - AI ADDENDUM
Version 1.0 (DRAFT) | Proposed Effective Date: February 15, 2026
Classification: Internal - Security Team

1. OVERVIEW

This addendum extends the organization's existing Incident Response Plan (IRP) to address security incidents specifically related to AI coding assistant usage. It defines additional incident categories, response procedures, and escalation paths unique to AI tool deployments.

2. AI-SPECIFIC INCIDENT CATEGORIES

  Category A - Data Leakage via AI Tool
  Severity: Critical
  Description: Confidential or restricted data transmitted to an AI service outside of approved channels or in violation of DLP policies.

  Category B - Unauthorized AI Access
  Severity: High
  Description: Use of AI tools by unauthorized personnel or through unapproved accounts/configurations.

  Category C - AI-Generated Vulnerability
  Severity: High
  Description: Security vulnerability introduced into production code that was generated by an AI coding assistant.

  Category D - Policy Violation
  Severity: Medium
  Description: Violation of the AI Acceptable Use Policy that does not result in immediate security impact.

3. RESPONSE PROCEDURES

[Additional response procedures and escalation paths to be finalized during review...]`,
    versions: [
      {
        version: "1.0",
        date: "Feb 1, 2026",
        author: "Michael Torres",
        summary: "Initial draft for review",
      },
    ],
    approvers: [
      {
        name: "Maria Lopez",
        role: "CISO",
        status: "pending",
      },
      {
        name: "Michael Torres",
        role: "Security Lead",
        status: "approved",
        date: "Feb 1, 2026",
      },
      {
        name: "Rachel Foster",
        role: "Legal Counsel",
        status: "pending",
      },
    ],
  },
  {
    id: "pol-003",
    title: "Data Classification Framework",
    type: "Data Classification",
    status: "draft",
    version: "0.3",
    lastUpdated: "Feb 5, 2026",
    description:
      "Framework for classifying data types and sensitivity levels in the context of AI tool usage, defining what data can and cannot be processed by AI assistants.",
    content: `DATA CLASSIFICATION FRAMEWORK FOR AI TOOL USAGE
Version 0.3 (DRAFT) | Working Document
Classification: Internal - Governance Team

1. PURPOSE

This framework establishes data classification tiers specifically for determining what information may be processed by AI coding assistants. Each classification tier defines handling requirements, permitted AI interactions, and required safeguards.

2. CLASSIFICATION TIERS

  TIER 1 - PUBLIC
  Description: Information intended for public disclosure
  AI Usage: Permitted without restrictions
  Examples: Open-source code, public documentation, published APIs

  TIER 2 - INTERNAL
  Description: General business information not intended for public release
  AI Usage: Permitted within managed sandbox with standard controls
  Examples: Internal tools, non-sensitive application code, development utilities

  TIER 3 - CONFIDENTIAL
  Description: Sensitive business information requiring protection
  AI Usage: Permitted only with enhanced DLP controls and audit logging
  Examples: Proprietary algorithms, business logic, internal architecture documents

  TIER 4 - RESTRICTED
  Description: Highly sensitive information with regulatory or legal implications
  AI Usage: PROHIBITED - must not be processed by any AI tool
  Examples: PII, PHI, financial records, authentication secrets, encryption keys

3. CLASSIFICATION PROCEDURES

[Classification workflow and decision tree under development...]`,
    versions: [
      {
        version: "0.3",
        date: "Feb 5, 2026",
        author: "Anna Wright",
        summary: "Added Tier 3 and Tier 4 definitions",
      },
      {
        version: "0.2",
        date: "Jan 28, 2026",
        author: "Anna Wright",
        summary: "Expanded tier descriptions with examples",
      },
      {
        version: "0.1",
        date: "Jan 20, 2026",
        author: "Anna Wright",
        summary: "Initial framework outline",
      },
    ],
    approvers: [
      {
        name: "Maria Lopez",
        role: "CISO",
        status: "pending",
      },
      {
        name: "David Kim",
        role: "CTO",
        status: "pending",
      },
    ],
  },
  {
    id: "pol-004",
    title: "AI Risk Management Framework",
    type: "Risk Management",
    status: "draft",
    version: "0.1",
    lastUpdated: "Feb 8, 2026",
    description:
      "Comprehensive risk management framework for identifying, assessing, and mitigating risks associated with AI coding tool adoption across the enterprise.",
    content: `AI RISK MANAGEMENT FRAMEWORK
Version 0.1 (DRAFT) | Working Document
Classification: Internal - Governance Team

1. INTRODUCTION

This framework provides a structured approach to managing risks associated with the adoption and ongoing use of AI coding assistants. It aligns with the organization's existing Enterprise Risk Management (ERM) program and incorporates AI-specific risk categories and mitigation strategies.

2. RISK IDENTIFICATION

Risk categories specific to AI coding tool adoption:

  a) Technical Risks: Model reliability, code quality, integration failures
  b) Security Risks: Data leakage, unauthorized access, vulnerability injection
  c) Compliance Risks: Regulatory violations, audit failures, contractual breaches
  d) Operational Risks: Vendor dependency, service disruptions, skill degradation
  e) Financial Risks: Cost overruns, licensing disputes, ROI shortfalls
  f) Reputational Risks: Public incidents, customer concerns, media exposure

3. RISK ASSESSMENT METHODOLOGY

[Risk scoring matrix and assessment procedures under development...]`,
    versions: [
      {
        version: "0.1",
        date: "Feb 8, 2026",
        author: "Sarah Chen",
        summary: "Initial framework outline with risk categories",
      },
    ],
    approvers: [
      {
        name: "Maria Lopez",
        role: "CISO",
        status: "pending",
      },
      {
        name: "David Kim",
        role: "CTO",
        status: "pending",
      },
      {
        name: "Rachel Foster",
        role: "Legal Counsel",
        status: "pending",
      },
      {
        name: "Patricia Nguyen",
        role: "Executive Sponsor",
        status: "pending",
      },
    ],
  },
];

function getStatusBadgeClasses(status: Policy["status"]): string {
  switch (status) {
    case "approved":
      return "bg-emerald-500/15 text-emerald-700 border-emerald-500/25";
    case "in_review":
      return "bg-amber-500/15 text-amber-700 border-amber-500/25";
    case "draft":
      return "bg-slate-100 text-slate-500 border-slate-200";
    default:
      return "bg-slate-100 text-slate-500 border-slate-200";
  }
}

function getStatusLabel(status: Policy["status"]): string {
  switch (status) {
    case "approved":
      return "Approved";
    case "in_review":
      return "In Review";
    case "draft":
      return "Draft";
    default:
      return status;
  }
}

function getStatusIcon(status: Policy["status"]): React.ReactNode {
  switch (status) {
    case "approved":
      return <CheckCircle2 className="h-3.5 w-3.5" />;
    case "in_review":
      return <Clock className="h-3.5 w-3.5" />;
    case "draft":
      return <AlertCircle className="h-3.5 w-3.5" />;
    default:
      return null;
  }
}

function getApproverStatusClasses(
  status: Approver["status"]
): string {
  switch (status) {
    case "approved":
      return "text-emerald-700";
    case "pending":
      return "text-amber-700";
    case "rejected":
      return "text-red-700";
    default:
      return "text-slate-500";
  }
}

export default function GovernancePoliciesPage({
  params,
}: {
  params: Promise<{ id: string }>;
}): React.ReactElement {
  const { id } = React.use(params);
  const { data: fetchedPolicies, isLoading, error } = usePolicies(id);

  const [expandedPolicy, setExpandedPolicy] = React.useState<string | null>(
    null
  );
  const [editingPolicy, setEditingPolicy] = React.useState<string | null>(null);
  const [editContent, setEditContent] = React.useState<string>("");
  const [showNewPolicyDialog, setShowNewPolicyDialog] = React.useState(false);
  const [newPolicyTitle, setNewPolicyTitle] = React.useState("");
  const [newPolicyType, setNewPolicyType] = React.useState("Acceptable Use");
  const [newPolicyDescription, setNewPolicyDescription] = React.useState("");
  const [localPolicies, setLocalPolicies] = React.useState<Policy[]>([]);

  if (isLoading) return <div className="flex justify-center p-8"><div className="animate-spin h-8 w-8 border-2 border-slate-900 border-t-transparent rounded-full" /></div>;
  if (error) return <div className="p-8 text-center"><p className="text-red-600">Error: {error.message}</p></div>;

  const basePolicies: Policy[] = (fetchedPolicies && fetchedPolicies.length > 0) ? fetchedPolicies as unknown as Policy[] : DEMO_POLICIES;
  const policies: Policy[] = [...basePolicies, ...localPolicies];

  const handleToggleExpand = (policyId: string): void => {
    if (expandedPolicy === policyId) {
      setExpandedPolicy(null);
      setEditingPolicy(null);
    } else {
      setExpandedPolicy(policyId);
      setEditingPolicy(null);
    }
  };

  const handleEdit = (policy: Policy): void => {
    setExpandedPolicy(policy.id);
    setEditingPolicy(policy.id);
    setEditContent(policy.content);
  };

  const handleCancelEdit = (): void => {
    setEditingPolicy(null);
    setEditContent("");
  };

  const handleSaveEdit = (): void => {
    if (!editingPolicy) return;
    setLocalPolicies((prev) =>
      prev.map((p) =>
        p.id === editingPolicy
          ? { ...p, content: editContent, lastUpdated: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) }
          : p
      )
    );
    setEditingPolicy(null);
    setEditContent("");
  };

  const handleCreatePolicy = (): void => {
    if (!newPolicyTitle.trim()) return;
    const newPolicy: Policy = {
      id: `pol-new-${Date.now()}`,
      title: newPolicyTitle.trim(),
      type: newPolicyType,
      status: "draft",
      version: "0.1",
      lastUpdated: new Date().toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
      }),
      description: newPolicyDescription.trim() || "New policy document",
      content: `${newPolicyTitle.trim().toUpperCase()}\nVersion 0.1 (DRAFT) | Working Document\n\n1. PURPOSE\n\n[Enter the purpose of this policy here...]\n\n2. SCOPE\n\n[Define who and what this policy covers...]\n\n3. POLICY STATEMENTS\n\n[Add policy statements here...]\n`,
      versions: [
        {
          version: "0.1",
          date: new Date().toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          }),
          author: "Current User",
          summary: "Initial draft",
        },
      ],
      approvers: [],
    };
    setLocalPolicies((prev) => [...prev, newPolicy]);
    setShowNewPolicyDialog(false);
    setNewPolicyTitle("");
    setNewPolicyType("Acceptable Use");
    setNewPolicyDescription("");
    // Auto-expand the newly created policy in edit mode
    setExpandedPolicy(newPolicy.id);
    setEditingPolicy(newPolicy.id);
    setEditContent(newPolicy.content);
  };

  return (
    <div className="flex flex-col gap-6 p-6">
      {/* New Policy Dialog */}
      <Dialog open={showNewPolicyDialog} onOpenChange={setShowNewPolicyDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create New Policy</DialogTitle>
            <DialogDescription>
              Create a new governance policy document. You can edit the full
              content after creation.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="policy-title">Policy Title</Label>
              <Input
                id="policy-title"
                placeholder="e.g. AI Acceptable Use Policy"
                value={newPolicyTitle}
                onChange={(e) => setNewPolicyTitle(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="policy-type">Policy Type</Label>
              <select
                id="policy-type"
                value={newPolicyType}
                onChange={(e) => setNewPolicyType(e.target.value)}
                className="flex h-9 w-full rounded-md border border-slate-200 bg-white px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-slate-400"
              >
                <option value="Acceptable Use">Acceptable Use</option>
                <option value="Incident Response">Incident Response</option>
                <option value="Data Classification">Data Classification</option>
                <option value="Risk Management">Risk Management</option>
                <option value="Access Control">Access Control</option>
                <option value="Compliance">Compliance</option>
                <option value="Other">Other</option>
              </select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="policy-description">Description</Label>
              <Textarea
                id="policy-description"
                placeholder="Brief description of the policy's purpose and scope..."
                value={newPolicyDescription}
                onChange={(e) => setNewPolicyDescription(e.target.value)}
                rows={3}
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setShowNewPolicyDialog(false)}
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreatePolicy}
              disabled={!newPolicyTitle.trim()}
              className="bg-slate-900 text-white hover:bg-slate-800"
            >
              Create Policy
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900">
            Governance Policies
          </h1>
          <p className="mt-1 text-sm text-slate-500">
            Manage AI governance policy documents, track versions, and route
            approvals.
          </p>
        </div>
        <Button
          onClick={() => setShowNewPolicyDialog(true)}
          className="bg-slate-900 text-white hover:bg-slate-800"
        >
          <Plus className="h-4 w-4" />
          New Policy
        </Button>
      </div>

      <Separator />

      {/* Policy Summary Stats */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-slate-100">
                <FileText className="h-5 w-5 text-slate-900" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">{policies.length}</p>
                <p className="text-xs text-slate-500">Total Policies</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-500/10">
                <CheckCircle2 className="h-5 w-5 text-emerald-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">{policies.filter(p => p.status === 'approved').length}</p>
                <p className="text-xs text-slate-500">Approved</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-amber-500/10">
                <Clock className="h-5 w-5 text-amber-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">{policies.filter(p => p.status === 'in_review').length}</p>
                <p className="text-xs text-slate-500">In Review</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-slate-100">
                <AlertCircle className="h-5 w-5 text-slate-500" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">{policies.filter(p => p.status === 'draft').length}</p>
                <p className="text-xs text-slate-500">Drafts</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Policy List */}
      <div className="flex flex-col gap-4">
        {policies.map((policy) => {
          const isExpanded = expandedPolicy === policy.id;
          const isEditing = editingPolicy === policy.id;

          return (
            <Card key={policy.id} className="overflow-hidden">
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <Badge
                        variant="outline"
                        className="text-xs font-medium"
                      >
                        {policy.type}
                      </Badge>
                      <Badge
                        variant="outline"
                        className={cn(
                          "text-xs font-medium flex items-center gap-1",
                          getStatusBadgeClasses(policy.status)
                        )}
                      >
                        {getStatusIcon(policy.status)}
                        {getStatusLabel(policy.status)}
                      </Badge>
                    </div>
                    <CardTitle className="text-lg">{policy.title}</CardTitle>
                    <CardDescription className="mt-1.5">
                      {policy.description}
                    </CardDescription>
                    <div className="mt-2 flex items-center gap-4 text-xs text-slate-500">
                      <span className="flex items-center gap-1">
                        <History className="h-3 w-3" />
                        Version {policy.version}
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock className="h-3 w-3" />
                        Updated {policy.lastUpdated}
                      </span>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleToggleExpand(policy.id)}
                    >
                      <Eye className="h-3.5 w-3.5" />
                      {isExpanded ? "Close" : "View"}
                      {isExpanded ? (
                        <ChevronUp className="h-3.5 w-3.5" />
                      ) : (
                        <ChevronDown className="h-3.5 w-3.5" />
                      )}
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleEdit(policy)}
                    >
                      <Pencil className="h-3.5 w-3.5" />
                      Edit
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => {
                      const blob = new Blob([`${policy.title}\nStatus: ${policy.status}\nVersion: ${policy.version}\nLast Updated: ${policy.lastUpdated}\n\n${policy.content}`], { type: 'text/plain' });
                      const url = URL.createObjectURL(blob);
                      const a = document.createElement('a');
                      a.href = url;
                      a.download = `${policy.title.replace(/\s+/g, '_')}.txt`;
                      a.click();
                      URL.revokeObjectURL(url);
                    }}>
                      <Download className="h-3.5 w-3.5" />
                      Export
                    </Button>
                  </div>
                </div>
              </CardHeader>

              {/* Expanded Detail View */}
              {isExpanded && (
                <>
                  <Separator />
                  <CardContent className="pt-4">
                    <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
                      {/* Main Content Area */}
                      <div className="lg:col-span-2">
                        <div className="flex items-center justify-between mb-3">
                          <h3 className="text-sm font-semibold text-slate-900">
                            Policy Document
                          </h3>
                          {isEditing && (
                            <div className="flex items-center gap-2">
                              <Button size="sm" variant="outline" onClick={handleCancelEdit}>
                                <X className="h-3.5 w-3.5" />
                                Cancel
                              </Button>
                              <Button size="sm" onClick={handleSaveEdit} className="bg-slate-900 text-white hover:bg-slate-800">
                                Save Changes
                              </Button>
                            </div>
                          )}
                        </div>
                        {isEditing ? (
                          <Textarea
                            value={editContent}
                            onChange={(e) => setEditContent(e.target.value)}
                            className="min-h-[500px] font-mono text-sm leading-relaxed"
                          />
                        ) : (
                          <div className="rounded-lg border border-slate-200 bg-slate-100/30 p-6">
                            <pre className="whitespace-pre-wrap font-mono text-sm leading-relaxed text-slate-900">
                              {policy.content}
                            </pre>
                          </div>
                        )}
                      </div>

                      {/* Sidebar */}
                      <div className="flex flex-col gap-6">
                        {/* Approval Status */}
                        <div>
                          <h3 className="text-sm font-semibold text-slate-900 mb-3">
                            Approval Status
                          </h3>
                          <div className="rounded-lg border border-slate-200 p-4 space-y-3">
                            {policy.approvers.map((approver, idx) => (
                              <div
                                key={idx}
                                className="flex items-center justify-between"
                              >
                                <div className="flex items-center gap-2">
                                  <div className="flex h-7 w-7 items-center justify-center rounded-full bg-slate-100">
                                    <User className="h-3.5 w-3.5 text-slate-500" />
                                  </div>
                                  <div>
                                    <p className="text-sm font-medium text-slate-900">
                                      {approver.name}
                                    </p>
                                    <p className="text-xs text-slate-500">
                                      {approver.role}
                                    </p>
                                  </div>
                                </div>
                                <div className="text-right">
                                  <p
                                    className={cn(
                                      "text-xs font-medium capitalize",
                                      getApproverStatusClasses(approver.status)
                                    )}
                                  >
                                    {approver.status}
                                  </p>
                                  {approver.date && (
                                    <p className="text-xs text-slate-500">
                                      {approver.date}
                                    </p>
                                  )}
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>

                        {/* Version History */}
                        <div>
                          <h3 className="text-sm font-semibold text-slate-900 mb-3">
                            Version History
                          </h3>
                          <div className="rounded-lg border border-slate-200 p-4">
                            <div className="space-y-4">
                              {policy.versions.map((ver, idx) => (
                                <div key={idx} className="relative">
                                  {idx < policy.versions.length - 1 && (
                                    <div className="absolute left-[9px] top-5 h-full w-px bg-slate-200" />
                                  )}
                                  <div className="flex gap-3">
                                    <div className="mt-0.5 flex h-[18px] w-[18px] shrink-0 items-center justify-center rounded-full border-2 border-slate-200 bg-white">
                                      <div
                                        className={cn(
                                          "h-2 w-2 rounded-full",
                                          idx === 0
                                            ? "bg-slate-900"
                                            : "bg-slate-100-foreground/40"
                                        )}
                                      />
                                    </div>
                                    <div className="pb-1">
                                      <div className="flex items-center gap-2">
                                        <span className="text-sm font-medium text-slate-900">
                                          v{ver.version}
                                        </span>
                                        <span className="text-xs text-slate-500">
                                          {ver.date}
                                        </span>
                                      </div>
                                      <p className="text-xs text-slate-500 mt-0.5">
                                        {ver.author}
                                      </p>
                                      <p className="text-xs text-slate-500 mt-0.5">
                                        {ver.summary}
                                      </p>
                                    </div>
                                  </div>
                                </div>
                              ))}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </>
              )}
            </Card>
          );
        })}
      </div>
    </div>
  );
}
